package com.multi.data.dao;

import com.multi.data.model.MultiUser;
import org.springframework.stereotype.Repository;

import java.util.List;


public interface MultiUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multi_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multi_user
     *
     * @mbg.generated
     */
    int insert(MultiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multi_user
     *
     * @mbg.generated
     */
    MultiUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multi_user
     *
     * @mbg.generated
     */
    List<MultiUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multi_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MultiUser record);
}